//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoYoga_PixelPulse {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoYoga_PixelPulse.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a abajo.
        /// </summary>
        internal static string abajo {
            get {
                return ResourceManager.GetString("abajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a árbol.
        /// </summary>
        internal static string arbol {
            get {
                return ResourceManager.GetString("arbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a arriba.
        /// </summary>
        internal static string arriba {
            get {
                return ResourceManager.GetString("arriba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cabeza.
        /// </summary>
        internal static string cabeza {
            get {
                return ResourceManager.GetString("cabeza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cadáver.
        /// </summary>
        internal static string cadaver {
            get {
                return ResourceManager.GetString("cadaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cobra.
        /// </summary>
        internal static string cobra {
            get {
                return ResourceManager.GetString("cobra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guerrero.
        /// </summary>
        internal static string guerrero {
            get {
                return ResourceManager.GetString("guerrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a guirnalda.
        /// </summary>
        internal static string guirnalda {
            get {
                return ResourceManager.GetString("guirnalda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a invertido.
        /// </summary>
        internal static string invertido {
            get {
                return ResourceManager.GetString("invertido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mano.
        /// </summary>
        internal static string mano {
            get {
                return ResourceManager.GetString("mano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mitad.
        /// </summary>
        internal static string mitad {
            get {
                return ResourceManager.GetString("mitad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a montaña.
        /// </summary>
        internal static string montania {
            get {
                return ResourceManager.GetString("montania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a niño.
        /// </summary>
        internal static string ninio {
            get {
                return ResourceManager.GetString("ninio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a oeste.
        /// </summary>
        internal static string oeste {
            get {
                return ResourceManager.GetString("oeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a paloma.
        /// </summary>
        internal static string paloma {
            get {
                return ResourceManager.GetString("paloma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a perro.
        /// </summary>
        internal static string perro {
            get {
                return ResourceManager.GetString("perro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pez.
        /// </summary>
        internal static string pez {
            get {
                return ResourceManager.GetString("pez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pie.
        /// </summary>
        internal static string pie {
            get {
                return ResourceManager.GetString("pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a postura.
        /// </summary>
        internal static string postura {
            get {
                return ResourceManager.GetString("postura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a puente.
        /// </summary>
        internal static string puente {
            get {
                return ResourceManager.GetString("puente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a real.
        /// </summary>
        internal static string real {
            get {
                return ResourceManager.GetString("real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rodilla.
        /// </summary>
        internal static string rodilla {
            get {
                return ResourceManager.GetString("rodilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rostro.
        /// </summary>
        internal static string rostro {
            get {
                return ResourceManager.GetString("rostro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a triángulo.
        /// </summary>
        internal static string triangulo {
            get {
                return ResourceManager.GetString("triangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uno.
        /// </summary>
        internal static string uno {
            get {
                return ResourceManager.GetString("uno", resourceCulture);
            }
        }
    }
}
